name: Deploy to two servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to PEDRAJA_SSH_HOST
        uses: ./deploy/action.yml
        with:
          compose-name: "pedraja-docker"
          ssh-host: ${{ secrets.PEDRAJA_SSH_HOST }}
          ssh-user: "docker-deploy"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to PEDRAJA_SSH_HOST_2
        uses: ./deploy/action.yml
        with:
          compose-name: "pedraja-docker"
          ssh-host: ${{ secrets.PEDRAJA_SSH_HOST_2 }}
          ssh-user: "docker-deploy"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
